// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDANjZwIKrl2_SYXD_mMDpECze9vngb1oU',
    appId: '1:518720610015:android:3c018889a1e2ff9eecd36a',
    messagingSenderId: '518720610015',
    projectId: 'qr-sisitt',
    storageBucket: 'qr-sisitt.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHtXPya0gqIJVNc8MOXmeMzCmi_bDWXDs',
    appId: '1:518720610015:ios:28395905a1961ed7ecd36a',
    messagingSenderId: '518720610015',
    projectId: 'qr-sisitt',
    storageBucket: 'qr-sisitt.appspot.com',
    iosClientId: '518720610015-1s5kgkhgc2ff9jhl0a9u8mnumsqund9s.apps.googleusercontent.com',
    iosBundleId: 'com.example.qrcode',
  );
}
